In [5]:
import pandas as pd
import glob

directory_path = '/Users/jangminsoo/Desktop/dev/pro/Medical-project/postgresql/sick'
csv_files = glob.glob(f"{directory_path}/*.csv")
df_all = [pd.read_csv(file) for file in csv_files]

# 모든 DataFrame을 하나로 통합
df = pd.concat(df_all, ignore_index=True)

# 결과 DataFrame 확인
print(df)


             병명                                                 정의  \
0      반사회적인격장애  미국정신의학회(American Psychiatric Association)가 201...   
1          발목염좌  발목염좌는 흔한 손상 중 하나로 발목이 심하게 꼬이거나 접질렸을 때 발목관절을 지탱...   
2          안과검사  안과 진찰 문진 후에 시진, 기본검사, 정밀검사 및 특수검사의 순서로 진행한다. 일...   
3       자궁내경관용종  용종(polyp; 폴립)이란 정상조직이 부분적으로 과도하게 증식하여 돌기 모양으로 ...   
4      심장자기공명영상  심장 자기공명영상 검사는 최근 기술의 발달로 빠른 시간 안에 영상을 얻어 움직이는 ...   
...         ...                                                ...   
1752  손발저림,감각없음  신경과 외래를 방문하는 많은 환자들이 "손발이 저리다", "감각이 없다", "남의 ...   
1753        편두통  일반적으로 편두통은 일상생활 또는 업무에 불편한 두통과 위장관 증상을 동반한 경우로...   
1754      만성췌장염  만성 췌장염의 전통적인 정의는 만성 염증, 섬유화 및 외분비와 내분비 조직의 파괴를...   
1755    망막색소변성증  망막색소변성증은 유전성 및 진행성으로 망막기능저하, 세포소실, 그리고 궁극적으로 망...   
1756       열과민증  외부의 온도상승에 대해 비정상적으로 불편하여 더위를 못 참는 상태를 나타내는 말로,...   

                                                     원인  \
0     유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1     발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 

## 데이터 확인 및 Copy로 원본 저장

In [6]:
dfc = df.copy()

In [7]:
dfc.__len__()

1757

In [8]:
dfc = dfc[['병명', '원인', '증상', '치료', '예방방법']]
dfc

병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
2          안과검사                                                NaN   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
4      심장자기공명영상                                                NaN   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
2                                                   NaN   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
4                                                   NaN   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  \
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...   
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...   
2                                                   NaN   
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...   
4                                                   NaN   
...                                                 ...   
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...   
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...   
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...   
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...   
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...   

                                                   예방방법  
0     양육 과정에서 폭력이나 착취, 학대를 경험하지 않도록 해야 한다. 그 외에 특별한 ...  
1     발목염좌를 예방하는 가장 좋은 방법은 발목 주변 근력을 균형적으로 유지하고, 유연성...  
2                                                   NaN  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
1752                                                NaN  
1753  일상적인 생활을 방해하는 두통 발작이 반복적으로 일어날 때 급성기치료가 힘든 상황이...  
1754  만성 췌장염의 예방을 위한 특별한 방법은 없다. 과도한 음주 및 흡연과 고단백 고지...  
1755  질병의 발병을 예방할 수 있는 방법은 아직까지 없으며 병의 진행 속도를 늦추기 위해...  
1756  열과민증을 유발할 수 있는 암페타민, 카페인, 식욕억제제 등의 복용을 피하며, 불안...  

[1757 rows x 5 columns]

## 결측치 삭제

In [9]:
dfc_clean = dfc.dropna(subset=['병명', '원인', '증상', '치료'])
dfc_clean

병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...   
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  \
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...   
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...   
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...   
6     1) ASCUS(Atypical Squamous Cells of Undetermin...   
7     증상이 없으면 치료가 필요 없다. 하지만 담낭선근증 환자에서 통증이 있거나 담석을 ...   
...                                                 ...   
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...   
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...   
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...   
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...   
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...   

                                                   예방방법  
0     양육 과정에서 폭력이나 착취, 학대를 경험하지 않도록 해야 한다. 그 외에 특별한 ...  
1     발목염좌를 예방하는 가장 좋은 방법은 발목 주변 근력을 균형적으로 유지하고, 유연성...  
3                                                   NaN  
6     자궁경부암 백신을 통해서 HPV 감염을 예방할 수 있으며, 현재 상용화 되어 있는 ...  
7     담낭선근증의 발생원인은 아직 명확히 밝혀져 있지 않으며 양성 질환으로 예방이 필요하...  
...                                                 ...  
1752                                                NaN  
1753  일상적인 생활을 방해하는 두통 발작이 반복적으로 일어날 때 급성기치료가 힘든 상황이...  
1754  만성 췌장염의 예방을 위한 특별한 방법은 없다. 과도한 음주 및 흡연과 고단백 고지...  
1755  질병의 발병을 예방할 수 있는 방법은 아직까지 없으며 병의 진행 속도를 늦추기 위해...  
1756  열과민증을 유발할 수 있는 암페타민, 카페인, 식욕억제제 등의 복용을 피하며, 불안...  

[1222 rows x 5 columns]

## 예방 방법의 결측치가 적으면 찾아서 넣으려 했으나, 결측치가 너무 많아서 예방 방법도 drop

In [10]:
dfc_clean[dfc_clean['예방방법'].isnull()]['병명'].__len__()

347

In [11]:
dfc_clean.drop(columns='예방방법')

병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...   
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...  
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...  
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...  
6     1) ASCUS(Atypical Squamous Cells of Undetermin...  
7     증상이 없으면 치료가 필요 없다. 하지만 담낭선근증 환자에서 통증이 있거나 담석을 ...  
...                                                 ...  
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...  
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...  
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...  
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...  
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...  

[1222 rows x 4 columns]

In [12]:
dfc_clean[dfc_clean['병명'] == '발목염좌']['치료']

1    1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...
Name: 치료, dtype: object

In [ ]:
# # 데이터프레임의 각 행을 병명, 원인, 증상, 치료 정보를 포함하는 하나의 텍스트로 변환
# dfc_clean["text"] = dfc_clean.apply(lambda row: f"병명: {row['병명']}\n원인: {row['원인']}\n증상: {row['증상']}\n치료: {row['치료']}", axis=1)

# # 변환된 텍스트와 병명만 포함하는 새로운 데이터프레임 생성
# df_for_rag = dfc_clean[["병명", "text"]]

# df_for_rag.head()


## 증상이랑 병명만 해서 rag Model이 병명을 잘 도출하는 지 확인

In [13]:
df_two = dfc_clean.copy()

In [14]:
df_two = df_two[['증상','병명']]

In [15]:
df_two

증상         병명
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   반사회적인격장애
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...       발목염좌
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...    자궁내경관용종
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...  자궁경부비정형세포
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...      담낭벽비후
...                                                 ...        ...
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...  손발저림,감각없음
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...        편두통
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...      만성췌장염
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...    망막색소변성증
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...       열과민증

[1222 rows x 2 columns]

In [18]:
df_two['증상']

0       다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...
1       통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...
3       자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...
6       대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...
7       일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...
                              ...                        
1752    흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...
1753    1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...
1754    만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...
1755    망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...
1756    증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...
Name: 증상, Length: 1222, dtype: object

In [20]:
# import chromadb
# from langchain_community.embeddings import HuggingFaceEmbeddings
# from langchain import hub
# from langchain_openai import ChatOpenAI
# from langchain_community.embeddings.sentence_transformer import (
#     SentenceTransformerEmbeddings,
# )

In [25]:
# from sentence_transformers import SentenceTransformer
# import pandas as pd
# import numpy as np
# import faiss

In [27]:
# embedding_function = SentenceTransformer("all-MiniLM-L6-v2")

In [28]:
# dfc_clean['병명'] = dfc_clean['병명'].apply(lambda x: embedding_function.encode(x, convert_to_tensor=True))

/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_99517/2699974321.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_clean['병명'] = dfc_clean['병명'].apply(lambda x: embedding_function.encode(x, convert_to_tensor=True))


## 그래프 db 제작

In [2]:
pip install neo4j

  Using cached neo4j-5.18.0-py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.


In [19]:
from neo4j import GraphDatabase

uri = "bolt://localhost:7687"
username = "neo4j"
password = "1234"

# Neo4j 세션 생성
driver = GraphDatabase.driver(uri, auth=(username, password))

In [16]:
dfc_clean

병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...   
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  \
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...   
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...   
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...   
6     1) ASCUS(Atypical Squamous Cells of Undetermin...   
7     증상이 없으면 치료가 필요 없다. 하지만 담낭선근증 환자에서 통증이 있거나 담석을 ...   
...                                                 ...   
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...   
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...   
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...   
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...   
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...   

                                                   예방방법  
0     양육 과정에서 폭력이나 착취, 학대를 경험하지 않도록 해야 한다. 그 외에 특별한 ...  
1     발목염좌를 예방하는 가장 좋은 방법은 발목 주변 근력을 균형적으로 유지하고, 유연성...  
3                                                   NaN  
6     자궁경부암 백신을 통해서 HPV 감염을 예방할 수 있으며, 현재 상용화 되어 있는 ...  
7     담낭선근증의 발생원인은 아직 명확히 밝혀져 있지 않으며 양성 질환으로 예방이 필요하...  
...                                                 ...  
1752                                                NaN  
1753  일상적인 생활을 방해하는 두통 발작이 반복적으로 일어날 때 급성기치료가 힘든 상황이...  
1754  만성 췌장염의 예방을 위한 특별한 방법은 없다. 과도한 음주 및 흡연과 고단백 고지...  
1755  질병의 발병을 예방할 수 있는 방법은 아직까지 없으며 병의 진행 속도를 늦추기 위해...  
1756  열과민증을 유발할 수 있는 암페타민, 카페인, 식욕억제제 등의 복용을 피하며, 불안...  

[1222 rows x 5 columns]

In [17]:
def add_disease_to_graph(tx, name, symptoms, causes, treatments):
    query = (
        "MERGE (d:Disease {name: $name}) "
        "WITH d "
        "UNWIND $symptoms AS symptom "
        "MERGE (s:Symptom {name: symptom}) "
        "MERGE (d)-[:HAS_SYMPTOM]->(s) "
        "WITH d "
        "UNWIND $causes AS cause "
        "MERGE (c:Cause {name: cause}) "
        "MERGE (d)-[:HAS_CAUSE]->(c) "
        "WITH d "
        "UNWIND $treatments AS treatment "
        "MERGE (t:Treatment {name: treatment}) "
        "MERGE (d)-[:HAS_TREATMENT]->(t)"
    )
    tx.run(query, name=name, symptoms=symptoms.split(', '), causes=causes.split(', '), treatments=treatments.split(', '))


In [18]:
with driver.session() as session:
    for index, row in dfc_clean.iterrows():
        session.write_transaction(add_disease_to_graph, row['병명'], row['증상'], row['원인'], row['치료'])


/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_75099/1025225192.py:3: DeprecationWarning: write_transaction has been renamed to execute_write
  session.write_transaction(add_disease_to_graph, row['병명'], row['증상'], row['원인'], row['치료'])
Transaction failed and will be retried in 1.014056961052715s (Couldn't connect to localhost:7687 (resolved to ()):
Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 61] Connection refused)
Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 61] Connection refused))
Transaction failed and will be retried in 1.9368682240065898s (Couldn't connect to localhost:7687 (resolved to ()):
Failed to establish connection to ResolvedIPv6Address(('::1', 7687, 0, 0)) (reason [Errno 61] Connection refused)
Failed to establish connection to ResolvedIPv4Address(('127.0.0.1', 7687)) (reason [Errno 61] Connection refused))
Transaction failed and will be retried in 4.774367704686324s (C

KeyboardInterrupt: 

In [20]:
dfc_clean

병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...   
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  \
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...   
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...   
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...   
6     1) ASCUS(Atypical Squamous Cells of Undetermin...   
7     증상이 없으면 치료가 필요 없다. 하지만 담낭선근증 환자에서 통증이 있거나 담석을 ...   
...                                                 ...   
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...   
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...   
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...   
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...   
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...   

                                                   예방방법  
0     양육 과정에서 폭력이나 착취, 학대를 경험하지 않도록 해야 한다. 그 외에 특별한 ...  
1     발목염좌를 예방하는 가장 좋은 방법은 발목 주변 근력을 균형적으로 유지하고, 유연성...  
3                                                   NaN  
6     자궁경부암 백신을 통해서 HPV 감염을 예방할 수 있으며, 현재 상용화 되어 있는 ...  
7     담낭선근증의 발생원인은 아직 명확히 밝혀져 있지 않으며 양성 질환으로 예방이 필요하...  
...                                                 ...  
1752                                                NaN  
1753  일상적인 생활을 방해하는 두통 발작이 반복적으로 일어날 때 급성기치료가 힘든 상황이...  
1754  만성 췌장염의 예방을 위한 특별한 방법은 없다. 과도한 음주 및 흡연과 고단백 고지...  
1755  질병의 발병을 예방할 수 있는 방법은 아직까지 없으며 병의 진행 속도를 늦추기 위해...  
1756  열과민증을 유발할 수 있는 암페타민, 카페인, 식욕억제제 등의 복용을 피하며, 불안...  

[1222 rows x 5 columns]

In [21]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


In [22]:
tfidf_vectorizer = TfidfVectorizer()

# 각 컬럼에 대해 TF-IDF 변환 수행
for column in ['병명', '증상', '원인', '치료']:
    tfidf_matrix = tfidf_vectorizer.fit_transform(dfc_clean[column])
    feature_names = tfidf_vectorizer.get_feature_names_out()
    
    # 변환된 특성 행렬과 특성 이름 출력 (예시)
    print(f"Column: {column}")
    print(f"Feature names: {feature_names}\n")
    print(tfidf_matrix.toarray(), "\n")

Column: 병명
Feature names: ['abo신생아용혈성질환' 'a형간염' 'b형간염' ... '흡인성폐렴' '히르슈슈프룽병' '히스테리구']

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

Column: 증상
Feature names: ['000' '000명의' '000여' ... '힘줄반사' '힘줄이' '힘줄이나']

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

Column: 원인
Feature names: ['000' '000m' '000mm3' ... '힘줄의' '힘줄이' '落傷']

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 

Column: 치료
Feature names: ['000' '000mg' '000ug씩' ... '힘줄이' '힘줄이나' '힘줄절개술']

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 



In [23]:
!pip install -qU \
    openai==1.6.1 \
    pinecone-client==3.1.0 \
    langchain==0.1.1 \
    langchain-community==0.0.13 \
    tiktoken==0.5.2 \
    datasets==2.12.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
langchain-openai 0.0.8 requires langchain-core<0.2.0,>=0.1.27, but you have langchain-core 0.1.23 which is incompatible.
langchain-openai 0.0.8 requires openai<2.0.0,>=1.10.0, but you have openai 1.6.1 which is incompatible.


In [24]:
pip install --upgrade "langchain-core>=0.1.27,<0.2.0" "openai>=1.10.0,<2.0.0"


  Using cached langchain_core-0.1.28-py3-none-any.whl.metadata (6.0 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.4/252.4 kB 2.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.4/227.4 kB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 7.8 MB/s eta 0:00:00
  Attempting uninstall: openai
    Found existing installation: openai 1.6.1
    Uninstalling openai-1.6.1:
      Successfully uninstalled openai-1.6.1
  Attempting uninstall: langsmith
    Found existing installation: langsmith 0.0.87
    Uninstalling langsmith-0.0.87:
      Successfully uninstalled langsmith-0.0.87
  Attempting uninstall: langchain-core
    Found existing installation: langchain-core 0.1.23
    Uninstalling langchain-core-0.1.23:
      Successfully uninstalled langchain-core-0.1.23
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.


In [25]:
# 데이터프레임의 각 행을 병명, 원인, 증상, 치료 정보를 포함하는 하나의 텍스트로 변환
dfc_clean["text"] = dfc_clean.apply(lambda row: f"병명: {row['병명']}\n원인: {row['원인']}\n증상: {row['증상']}\n치료: {row['치료']}", axis=1)

# 변환된 텍스트와 병명만 포함하는 새로운 데이터프레임 생성
df_for_rag = dfc_clean[["병명", "text"]]

df_for_rag.head()


/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_75099/964816452.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_clean["text"] = dfc_clean.apply(lambda row: f"병명: {row['병명']}\n원인: {row['원인']}\n증상: {row['증상']}\n치료: {row['치료']}", axis=1)


병명                                               text
0   반사회적인격장애  병명: 반사회적인격장애\n원인: 유전적인 요소가 많은 것으로 알려져 있다. 다만, ...
1       발목염좌  병명: 발목염좌\n원인: 발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗...
3    자궁내경관용종  병명: 자궁내경관용종\n원인: 자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 ...
6  자궁경부비정형세포  병명: 자궁경부비정형세포\n원인: 자궁경부에 인유두종바이러스(Human Papill...
7      담낭벽비후  병명: 담낭벽비후\n원인: 담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환...

In [27]:
df_for_rag[df_for_rag['병명']== '감기']

병명                                               text
1392  감기  병명: 감기\n원인: 200여개 이상의 서로 다른 종류의 바이러스가 감기를 일으킨다...

In [34]:
df_for_rag[df_for_rag['병명']== '감기']

병명                                               text
1392  감기  병명: 감기\n원인: 200여개 이상의 서로 다른 종류의 바이러스가 감기를 일으킨다...

## 증상 명사로 변경

In [35]:
pip install konlpy nltk

  Using cached lxml-5.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.5 kB)
Using cached konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.4/587.4 kB 3.8 MB/s eta 0:00:0000:0100:01
Using cached lxml-5.1.0-cp311-cp311-macosx_11_0_arm64.whl (4.5 MB)
Note: you may need to restart the kernel to use updated packages.


In [36]:
from konlpy.tag import Okt

# Okt 객체 생성
okt = Okt()

In [37]:
stopwords = ['이', '있', '하', '것', '들', '그', '되', '수', '보', '않', '없', '나', '사람', '주', '아니', '등', '같', '우리', '때', '년', '가', '한', '지', '대하', '오', '말', '일', '그렇', '위하']


In [39]:
# 증상 컬럼의 텍스트를 명사로 분석하고 불용어를 제거하는 함수
def extract_nouns_remove_stopwords(text):
    nouns = okt.nouns(text)
    nouns = [noun for noun in nouns if noun not in stopwords]
    return nouns

# 증상 컬럼에 함수 적용
dfc_clean['processed_증상'] = dfc_clean['증상'].apply(extract_nouns_remove_stopwords)

print(dfc_clean)

             병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중

/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_75099/3535782056.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_clean['processed_증상'] = dfc_clean['증상'].apply(extract_nouns_remove_stopwords)


In [40]:
dfc_clean['processed_증상']

0       [다른, 권리, 무시, 행동, 양식, 반복, 지속, 반복, 범법, 행위, 참여, 거...
1       [통증, 압통, 및, 종창, 부종, 전형, 증상, 급, 성기, 체중, 서기, 정도,...
3       [자궁, 경관, 용종, 대부분, 증상, 정기, 검진, 시, 의사, 발견, 증상, 경...
6       [대부분, 무증상, 경우, 외, 비정상, 질, 출혈, 성교, 시, 통증, 및, 출혈...
7       [일반, 증상, 영상, 검사, 발견, 경우, 담낭, 벽, 비후, 담관, 협착, 발생...
                              ...                        
1752    [손발, 저리, 증상, 의학, 감각, 이상, 주파수, 진동, 감각, 과, 느낌, 주...
1753    [무, 조짐, 편두통, 편두통, 보통, 전구, 증상, 조짐, 두통, 및, 동반, 증...
1754    [만성, 췌장염, 환자, 통증, 지속, 간, 적일, 통증, 수도, 점, 급성, 췌장...
1755    [망막색소변성증, 대표, 가지, 증상, 야맹증, 시야협착, 야맹증, 야간, 시력, ...
1756        [증상, 신체, 과열, 땀, 동반, 과민증, 보통, 증상, 시작, 장기간, 지속]
Name: processed_증상, Length: 1222, dtype: object

In [41]:
dfc_clean.columns


Index(['병명', '원인', '증상', '치료', '예방방법', 'text', 'processed_증상'], dtype='object')

In [42]:
dfc_clean['processed_원인'] = dfc_clean['원인'].apply(extract_nouns_remove_stopwords)

/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_75099/3239202250.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_clean['processed_원인'] = dfc_clean['원인'].apply(extract_nouns_remove_stopwords)


In [50]:
dfc_clean['processed_치료'] = dfc_clean['치료'].apply(extract_nouns_remove_stopwords)

/var/folders/pz/nvv7dzs52qs11nzxkh415khr0000gn/T/ipykernel_75099/275738399.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfc_clean['processed_치료'] = dfc_clean['치료'].apply(extract_nouns_remove_stopwords)


In [51]:
dfc_clean


병명                                                 원인  \
0      반사회적인격장애  유전적인 요소가 많은 것으로 알려져 있다. 다만, 반사회적 인격 자체가 유전되는 것...   
1          발목염좌  발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗어난 경우에 발생하게 된다...   
3       자궁내경관용종  자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 대한 국소적인 반응인지, 또는 ...   
6     자궁경부비정형세포  자궁경부에 인유두종바이러스(Human Papilloma Virus, HPV)의 지속...   
7         담낭벽비후  담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환자에서 발견된다. 90% 정...   
...         ...                                                ...   
1752  손발저림,감각없음  손발이 저린 증상은 말초신경을 구성하는 다양한 신경섬유 중 단면적이 커서 위치 및 ...   
1753        편두통  편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 없다. 이전에는 두피를 ...   
1754      만성췌장염  만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 5년 이상(일부 환자에서는 ...   
1755    망막색소변성증  망막색소변성증의 원인은 아직 명확하지 않으나 유전자 이상에 의한 것으로 생각한다. ...   
1756       열과민증  열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상선 기능 항진증, 폐경, ...   

                                                     증상  \
0     다른 사람의 권리를 무시하는 무책임한 행동 양식을 반복적, 지속적으로 보인다. 많은...   
1     통증, 압통 및 종창과 부종이 전형적인 증상으로 급성기에는 체중을 싣고 서기가 힘들...   
3     자궁내경관 용종은 대부분 증상이 없고 정기검진 시 의사에 의해 우연히 발견된다. 증...   
6     대부분은 무증상인 경우가 많으며, 그 외 비정상적인 질 출혈이나 성교 시 통증 및 ...   
7     일반적으로 증상을 일으키지 않으며 영상검사에서 우연히 발견하는 경우가 많다. 드물지...   
...                                                 ...   
1752  흔히 "손발이 저리다"라는 증상은 의학적으로 감각이상(paresthesia)라고 하...   
1753  1) 무조짐 편두통(migraine without aura)편두통은 보통 전구증상-...   
1754  만성 췌장염 환자의 통증은 지속적 간헐적일 수 있으며, 통증이 없을 수도 있다는 점...   
1755  망막색소변성증의 대표적인 2가지 증상으로 야맹증과 시야협착이 있다. 야맹증은 야간 ...   
1756  증상이 나타나면 신체가 과열된 것처럼 느껴지며, 땀 흘림을 동반하기도 한다. 열과민...   

                                                     치료  \
0     다른 정신질환으로 치료를 할 때 반사회적 인격장애 여부를 확인해야 한다. 피상적으로...   
1     1. 보존적 치료1) RICE 치료: 휴식(Rest), 냉찜질(Ice), 압박(Co...   
3     대부분의 자궁경관 용종은 양성이지만, 악성으로 변화되는 빈도가 약 0.2~1.5% ...   
6     1) ASCUS(Atypical Squamous Cells of Undetermin...   
7     증상이 없으면 치료가 필요 없다. 하지만 담낭선근증 환자에서 통증이 있거나 담석을 ...   
...                                                 ...   
1752  원인 질환의 치료에 준한다. 기존에 앓고 있는 특별한 질환이 없는 노인에서 통증 및...   
1753  효과적인 두통 치료를 위해서는 적절한 급성기 약물요법으로 통증을 완화시키면서 두통의...   
1754  만성 췌장염 환자의 치료는 두 가지 가장 큰 문제점인 통증과 영양 흡수 장애의 치료...   
1755  현재까지 망막색소변성의 근본적인 치료법은 없으나 여러 치료법이 연구 중에 있다. 이...   
1756  갑상선기능항진증에 의한 열과민증은 항갑상선제를 복용하면 점차 증상이 호전된다. 폐경...   

                                                   예방방법  \
0     양육 과정에서 폭력이나 착취, 학대를 경험하지 않도록 해야 한다. 그 외에 특별한 ...   
1     발목염좌를 예방하는 가장 좋은 방법은 발목 주변 근력을 균형적으로 유지하고, 유연성...   
3                                                   NaN   
6     자궁경부암 백신을 통해서 HPV 감염을 예방할 수 있으며, 현재 상용화 되어 있는 ...   
7     담낭선근증의 발생원인은 아직 명확히 밝혀져 있지 않으며 양성 질환으로 예방이 필요하...   
...                                                 ...   
1752                                                NaN   
1753  일상적인 생활을 방해하는 두통 발작이 반복적으로 일어날 때 급성기치료가 힘든 상황이...   
1754  만성 췌장염의 예방을 위한 특별한 방법은 없다. 과도한 음주 및 흡연과 고단백 고지...   
1755  질병의 발병을 예방할 수 있는 방법은 아직까지 없으며 병의 진행 속도를 늦추기 위해...   
1756  열과민증을 유발할 수 있는 암페타민, 카페인, 식욕억제제 등의 복용을 피하며, 불안...   

                                                   text  \
0     병명: 반사회적인격장애\n원인: 유전적인 요소가 많은 것으로 알려져 있다. 다만, ...   
1     병명: 발목염좌\n원인: 발목이 꼬이거나 접질려 정상적인 발목관절의 운동 범위를 벗...   
3     병명: 자궁내경관용종\n원인: 자궁경관 용종이 만성 염증에 의한 것인지, 호르몬에 ...   
6     병명: 자궁경부비정형세포\n원인: 자궁경부에 인유두종바이러스(Human Papill...   
7     병명: 담낭벽비후\n원인: 담낭선근증의 원인은 잘 밝혀져 있지 않으며 1-9%의 환...   
...                                                 ...   
1752  병명: 손발저림,감각없음\n원인: 손발이 저린 증상은 말초신경을 구성하는 다양한 신...   
1753  병명: 편두통\n원인: 편두통을 유발하는 원인에 대해서는 아직 정확히 알려진 바가 ...   
1754  병명: 만성췌장염\n원인: 만성 췌장염의 원인 중 가장 흔한 것은 음주이며, 최소 ...   
1755  병명: 망막색소변성증\n원인: 망막색소변성증의 원인은 아직 명확하지 않으나 유전자 ...   
1756  병명: 열과민증\n원인: 열과민증의 원인은 다양해서 정확한 진단이 필수적이다. 갑상...   

                                           processed_증상  \
0     [다른, 권리, 무시, 행동, 양식, 반복, 지속, 반복, 범법, 행위, 참여, 거...   
1     [통증, 압통, 및, 종창, 부종, 전형, 증상, 급, 성기, 체중, 서기, 정도,...   
3     [자궁, 경관, 용종, 대부분, 증상, 정기, 검진, 시, 의사, 발견, 증상, 경...   
6     [대부분, 무증상, 경우, 외, 비정상, 질, 출혈, 성교, 시, 통증, 및, 출혈...   
7     [일반, 증상, 영상, 검사, 발견, 경우, 담낭, 벽, 비후,

In [52]:
# 필요한 컬럼만 선택하여 새로운 데이터프레임 생성
df_selected = dfc_clean[['병명', 'processed_증상', 'processed_원인', 'processed_치료']]

print(df_selected)


             병명                                       processed_증상  \
0      반사회적인격장애  [다른, 권리, 무시, 행동, 양식, 반복, 지속, 반복, 범법, 행위, 참여, 거...   
1          발목염좌  [통증, 압통, 및, 종창, 부종, 전형, 증상, 급, 성기, 체중, 서기, 정도,...   
3       자궁내경관용종  [자궁, 경관, 용종, 대부분, 증상, 정기, 검진, 시, 의사, 발견, 증상, 경...   
6     자궁경부비정형세포  [대부분, 무증상, 경우, 외, 비정상, 질, 출혈, 성교, 시, 통증, 및, 출혈...   
7         담낭벽비후  [일반, 증상, 영상, 검사, 발견, 경우, 담낭, 벽, 비후, 담관, 협착, 발생...   
...         ...                                                ...   
1752  손발저림,감각없음  [손발, 저리, 증상, 의학, 감각, 이상, 주파수, 진동, 감각, 과, 느낌, 주...   
1753        편두통  [무, 조짐, 편두통, 편두통, 보통, 전구, 증상, 조짐, 두통, 및, 동반, 증...   
1754      만성췌장염  [만성, 췌장염, 환자, 통증, 지속, 간, 적일, 통증, 수도, 점, 급성, 췌장...   
1755    망막색소변성증  [망막색소변성증, 대표, 가지, 증상, 야맹증, 시야협착, 야맹증, 야간, 시력, ...   
1756       열과민증      [증상, 신체, 과열, 땀, 동반, 과민증, 보통, 증상, 시작, 장기간, 지속]   

                                           processed_원인  \
0     [유전, 요소, 다만, 사회, 인격, 자체, 유전, 충, 동성, 공격성, 기질, 유...   
1     [발목, 정상, 발목, 관절, 운동, 범위, 경우, 발생, 스포

In [53]:
df_selected.columns = ['병명', '증상', '원인', '치료']

In [56]:
print(df_selected)
df_selected.columns

             병명                                                 증상  \
0      반사회적인격장애  [다른, 권리, 무시, 행동, 양식, 반복, 지속, 반복, 범법, 행위, 참여, 거...   
1          발목염좌  [통증, 압통, 및, 종창, 부종, 전형, 증상, 급, 성기, 체중, 서기, 정도,...   
3       자궁내경관용종  [자궁, 경관, 용종, 대부분, 증상, 정기, 검진, 시, 의사, 발견, 증상, 경...   
6     자궁경부비정형세포  [대부분, 무증상, 경우, 외, 비정상, 질, 출혈, 성교, 시, 통증, 및, 출혈...   
7         담낭벽비후  [일반, 증상, 영상, 검사, 발견, 경우, 담낭, 벽, 비후, 담관, 협착, 발생...   
...         ...                                                ...   
1752  손발저림,감각없음  [손발, 저리, 증상, 의학, 감각, 이상, 주파수, 진동, 감각, 과, 느낌, 주...   
1753        편두통  [무, 조짐, 편두통, 편두통, 보통, 전구, 증상, 조짐, 두통, 및, 동반, 증...   
1754      만성췌장염  [만성, 췌장염, 환자, 통증, 지속, 간, 적일, 통증, 수도, 점, 급성, 췌장...   
1755    망막색소변성증  [망막색소변성증, 대표, 가지, 증상, 야맹증, 시야협착, 야맹증, 야간, 시력, ...   
1756       열과민증      [증상, 신체, 과열, 땀, 동반, 과민증, 보통, 증상, 시작, 장기간, 지속]   

                                                     원인  \
0     [유전, 요소, 다만, 사회, 인격, 자체, 유전, 충, 동성, 공격성, 기질, 유...   
1     [발목, 정상, 발목, 관절, 운동, 범위, 경우, 발생, 스포

Index(['병명', '증상', '원인', '치료'], dtype='object')

In [58]:
# df_selected 데이터프레임을 CSV 파일로 저장
df_selected.to_csv('/Users/jangminsoo/Desktop/dev/pro/Medical-project/csv_folder/merged3.csv', index=False)
